---
title: Broad characteristics
author: Gibran Hemani
date: 23/02/2019
---


```{r}
library(mrever)
connect()
library(dplyr)
library(data.table)
library(knitr)
library(ggplot2)
library(tidyr)

traits <- get_traits()
o <- list()
for(i in 1:8)
{
	message(i)

	a <- fread(paste0("zcat ../resources/neo4j_stage/mr", i, ".csv.gz"), he=i == 1, sep=",")
	if(i != 1) names(a) <- names(o[[1]])[-length(names(o[[1]]))]
	names(a) <- gsub(":FLOAT", "", names(a))
	names(a) <- gsub(":INT", "", names(a))
	names(a)[1:2] <- c("exposure", "outcome")
	a$id <- paste(a$exposure, a$outcome)
	a$exposure <- as.character(a$exposure)
	a$outcome <- as.character(a$outcome)
	k <- subset(a, method == "FE IVW" & selection == "Tophits" & nsnp > 5) %>% .$id
	a <- subset(a, paste(exposure, outcome) %in% k)
	o[[i]] <- a
}
o <- bind_rows(o)

moe1 <- subset(o, method == "Steiger null") %>% subset(!duplicated(id))
moe2 <- filter(o, ! id %in% moe1$id) %>% group_by(id) %>% arrange(desc(moescore)) %>% slice(1)

moe <- bind_rows(moe1, moe2)
table(moe$method, moe$selection)
table(moe$method)

moe$z <- abs(moe$b / moe$se)
moe$z[moe$z > 10] <- 10
table(z > 100)

table(a$method, a$selection)

ggplot(moe, aes(x=z)) +
geom_histogram(aes(fill=selection), position="dodge") +
facet_grid(method ~ .) +
theme(strip.text = element_text(angle=0))


```

## 1. Reverse direction results

```{r}

b <- subset(a, id %in% subset(a, method == "Steiger null")$id)
bsig <- subset(b, method == "RE IVW" & selection == "HF" & p.adjust(pval, "fdr") < 0.05)
bsig <- merge(bsig, subset(traits, select=c(bgcidId, trait)), by.x="exposure", by.y="bgcidId")
bsig <- merge(bsig, subset(traits, select=c(bgcidId, trait)), by.x="outcome", by.y="bgcidId")
subset(bsig, select=c(trait.x, trait.y)) %>% kable
```

## 2. Instrument selection


```{r}

library(data.table)
library(dplyr)
library(tidyr)
library(mrever)
library(ggplot2)
connect()


b <- subset(o, method %in% c("FE IVW", "Wald ratio", "Steiger null"))

traits <- get_traits() %>% dplyr::select(c(bgcidId, sample_size, trait, nsnp))
out <- group_by(b, exposure, outcome, selection) %>% 
summarise(instruments = first(nsnp)) %>% 
inner_join(., traits, by=c("exposure"="bgcidId"))


p <- tidyr::spread(o, key=selection, value=instruments)


save(out, file="out.rdata")

ggplot(out, aes(x=sample_size, y=instruments)) +
# geom_point(aes(colour=selection)) +
geom_smooth(aes(colour=selection))

out$n2 <- out$sample_size
out$n2[out$n2 > 500000] <- NA

out$nbin <- cut(out$n2, 10)
table(out$nbin)

ggplot(subset(out, !is.na(n2)), aes(x=nbin, y=instruments)) +
geom_boxplot(aes(fill=selection), position="dodge", outlier.shape=NA) +
scale_fill_brewer(type="qual") +
theme(axis.text.x=element_text(angle=90))


temp <- subset(out, selection %in% c("DF", "Tophits")) %>% 
group_by(exposure, outcome) %>%
summarise(nrev = abs(diff(instruments)))


temp <- tidyr::spread(out, key=selection, value=instruments)
temp$nrev <- temp$Tophits - temp$DF
summary(lm(nrev ~ I(n2/10000), temp))


## Import result:

temp$prev <- temp$nrev / temp$Tophits
summary(lm(prev ~ I(n2/100000), temp))
summary(temp$prev)

# Across 758955 MR analyses, for every 100k increase in sample size the proportion of instruments that are reverse causal increases by 2.8% (s.e. 0.023, p < 2e-16)


ggplot(temp, aes(x=n2, y=prev)) +
geom_point(alpha=0.4) +
geom_smooth() +
geom_smooth(method="lm")

ggplot(temp %>% filter(!is.na(n2)), aes(x=nbin, y=prev)) +
geom_boxplot()


temp2 <- group_by(temp, exposure, n2) %>%
summarise(
	mdf = mean(Tophits - DF), pmdf = mdf / max(Tophits),
	mhf = mean(Tophits - HF), pmhf = mhf / max(Tophits)
)

summary(lm(pmdf ~ n2, temp2))
summary(lm(pmhf ~ n2, temp2))


ggplot(temp2 %>% , aes(x=))

summary(lm(nrev ~ I(n2/1000), temp))



```


## 1. Compare causal effect estimates across ivw, ivw HF. 



What are notable discrepancies?

2. Compare 



